Improve error handling
Check argument count
Check if DIR was changed
Execute user specific shell
Improve #!

diff --git a/mkcd b/mkcd
--- a/mkcd
+++ b/mkcd
@@ -1,12 +1,22 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+if [ $# -ne 1 ]; then
+    echo -e "\nProvide one argument as directroy-name:\n  '${0} <directroy-name>'\n"
+    exit 1
+fi
 
 mkdir -p "${1}"
 
 if [ $? -ne 0 ]; then
-    echo "Couldn't create the directory: ${1}"
-    exit 1
+    echo "Could not create directory: ${1}"
+    exit 2
 fi
 
 cd "${1}"
 
-exec /bin/bash
+if [ $? -ne 0 ]; then
+    echo "Could not change to directory: ${1}"
+    exit 3
+fi
+
+exec $(readlink /proc/$$/exe)
